from abc import ABC, abstractmethod
from typing import Dict, Any

class PaymentProvider(ABC):
    @abstractmethod
    def create_payment_link(self, amount: float, currency: str, order_id: str, customer_phone: str) -> Dict[str, Any]:
        """
        Create a payment link for the order.
        
        Returns a dictionary containing:
        - provider_order_id: The ID generated by the provider
        - payment_url: The URL to send to the user (can be None if the provider doesn't use links)
        - ...any other provider-specific data
        """
        pass

    @abstractmethod
    def verify_webhook_signature(self, payload: bytes, signature: str) -> bool:
        """
        Verifies the authenticity of the webhook payload using the provider's signature.
        """
        pass
        
    @abstractmethod
    def parse_webhook_event(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Parses the provider's webhook payload and normalizes it.
        
        Returns a dictionary containing:
        - provider_event_id: Unique event ID for idempotency (e.g., 'ev_xxx')
        - provider_payment_id: The ID of the successful payment (e.g., 'pay_xxx')
        - provider_order_id: The original order ID (e.g., 'order_xxx')
        - status: Normalized status (e.g., 'captured', 'failed')
        """
        pass
