"""P0_A_schema_updates

Revision ID: 06b0f0e02c0a
Revises: 6740a9d4acf0
Create Date: 2026-09-10 15:00:25.721972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b0f0e02c0a'
down_revision: Union[str, Sequence[str], None] = '6740a9d4acf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    with op.batch_alter_table('products') as batch_op:
        batch_op.create_check_constraint('check_stock_non_negative', 'stock >= 0')
    
    # Data migration for roles
    op.execute("UPDATE users SET role = 'CUSTOMER' WHERE role = 'customer'")
    op.execute("UPDATE users SET role = 'SUPER_ADMIN' WHERE role = 'admin'")
    
    # Alter server default for new rows
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role', server_default='CUSTOMER')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert server default
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role', server_default='customer')
    
    # Revert Data migration
    op.execute("UPDATE users SET role = 'customer' WHERE role = 'CUSTOMER'")
    op.execute("UPDATE users SET role = 'admin' WHERE role = 'SUPER_ADMIN'")

    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('check_stock_non_negative', type_='check')
    with op.batch_alter_table('categories') as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
