"""add product detail attributes

Revision ID: 206b50924a1c
Revises: 22ff95d6bb82
Create Date: 2026-08-25 19:00:38.189608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206b50924a1c'
down_revision: Union[str, Sequence[str], None] = '22ff95d6bb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('colour', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('care', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('badge', sa.String(length=100), nullable=True))
        batch_op.alter_column('material',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('material',
                   existing_type=sa.String(length=255),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=True)
        batch_op.drop_column('badge')
        batch_op.drop_column('care')
        batch_op.drop_column('colour')
        batch_op.drop_column('details')
    # ### end Alembic commands ###
