"""add product detail attributes

Revision ID: 206b50924a1c
Revises: 22ff95d6bb82
Create Date: 2026-08-25 19:00:38.189608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206b50924a1c'
down_revision: Union[str, Sequence[str], None] = '22ff95d6bb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('colour', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('care', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('badge', sa.String(length=100), nullable=True))
    op.alter_column('products', 'material',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'material',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('products', 'badge')
    op.drop_column('products', 'care')
    op.drop_column('products', 'colour')
    op.drop_column('products', 'details')
    # ### end Alembic commands ###
