"""Add PaymentRefund model

Revision ID: 53c8c4ce7857
Revises: 1e20ba6a0a8d
Create Date: 2026-09-17 15:33:59.649558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c8c4ce7857'
down_revision: Union[str, Sequence[str], None] = '1e20ba6a0a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('provider_refund_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_refunds_id'), ['id'], unique=False)
        batch_op.create_index('ix_payment_refunds_one_pending_per_payment', ['payment_id'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
        batch_op.create_index(batch_op.f('ix_payment_refunds_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_refunds_provider_refund_id'), ['provider_refund_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_refunds_provider_refund_id'))
        batch_op.drop_index(batch_op.f('ix_payment_refunds_payment_id'))
        batch_op.drop_index('ix_payment_refunds_one_pending_per_payment', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_payment_refunds_id'))

    op.drop_table('payment_refunds')
    # ### end Alembic commands ###
