"""Add AdminAudit model

Revision ID: 58cc6b6cb945
Revises: c3ccf0348166
Create Date: 2026-09-18 11:34:15.595994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cc6b6cb945'
down_revision: Union[str, Sequence[str], None] = 'c3ccf0348166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_admin_audits_created_at_id', ['created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_id'), ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audits_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audits_entity_type'))
        batch_op.drop_index(batch_op.f('ix_admin_audits_entity_id'))
        batch_op.drop_index('ix_admin_audits_created_at_id')
        batch_op.drop_index(batch_op.f('ix_admin_audits_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audits_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audits_action'))

    op.drop_table('admin_audits')
    # ### end Alembic commands ###
