"""Add InventoryAudit model

Revision ID: c3ccf0348166
Revises: 53c8c4ce7857
Create Date: 2026-09-17 15:51:50.438573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ccf0348166'
down_revision: Union[str, Sequence[str], None] = '53c8c4ce7857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('adjustment', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('adjustment != 0', name='check_adjustment_not_zero'),
    sa.CheckConstraint('new_stock >= 0', name='check_new_stock_non_negative'),
    sa.CheckConstraint('previous_stock >= 0', name='check_previous_stock_non_negative'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_audit_adjustment_type'), ['adjustment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_audit_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_audit_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_audit_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_audit_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_audit_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_audit_order_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_audit_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_audit_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_audit_admin_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_audit_adjustment_type'))

    op.drop_table('inventory_audit')
    # ### end Alembic commands ###
